- name: Install nginx
  package:
    name: "{{ webserver }}"
    state: present

- name: deploy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

